### PR TITLE
Upgrade dependencies and fix warnings

### PR DESCRIPTION
**Pull request by blatyo**

### CODE REVIEW

**Comment by bhelx** [comment]
Thanks @blatyo !

Let me know if you have any issues or any more PRs. Happy to review and merge them.

**Comment by blatyo** [comment]
I was looking at upgrading this library to the newest API version. Do you have a recommended approach?

Also, you wrote:

```
Warning, this is alpha software and is not supported by Recurly. It should not be used in 
production yet unless you really know what you are doing. There are bugs and the API 
will likely change.
```

What are the bugs? Wouldn't the API changing not matter since Recurly supports old API versions? What things do you see preventing this library from being non-alpha?

**Comment by bhelx** [comment]
@blatyo That sounds great! Would love another set of eyes on this library and I can make time to help bring it up to date.

I'll try to address your comments individually:

> I was looking at upgrading this library to the newest API version. Do you have a recommended approach?

This library is currently on version `2.4` of the HTTP API. Recurly is currently on `2.8`. The best approach is to look at each version here: https://dev.recurly.com/page/api-release-notes

The strategy to upgrading is to read each version's changes (2.5, 2.6, 2.7, 2.8) and implement the changes described. I'd be happy to help out with this if you have some specific features in mind you wish to use. I think it would be great to get the [purchases feature](https://dev.recurly.com/docs/create-purchase)  in here.

> What are the bugs?

I have no idea, but I've never used this in a real production system and I can assume there are some obvious ones that will pop up. I'm using very small portions of it for side projects that aren't heavily used. I just wanted to warn people and let them know that I've not used this enough to find the bugs.

> Wouldn't the API changing not matter since Recurly supports old API versions?

In that statement I was not referring to the HTTP API, but rather the function level API this library exposes. For example, one change I had thought about implementing was moving all the functions out of the Resource modules and into a single module. You'd also explicitly instantiate the clients rather than having this implicit client creation. Example:

```elixir
# You can no longer do this. All HTTP functions will be moved to top level.
{:ok, account} = Recurly.Account.find("myaccountcode")

# You instead will be able to create a client and all functions will be in the Recurly module
{:ok, client} = Recurly.create_client(api_key: "abcdef1234567890", subdomain: "mysub")
{:ok, account} = Recurly.find_account(client, account_code: "myaccountcode")
```

This is just an example of what I meant by `the API will likely change`.

> What things do you see preventing this library from being non-alpha?

That's a good question. Off the top of my head, I was thinking these 4 things:

1. API finalized and agreed upon (for example, should we stick with the current API or switch to the Client approach listed above?).
2. Better documentation. The docs are pretty good but I'd like to see a little more thought put into the overview section.
3. Some of the items in the `TODO` section on the `README` are important.
4. At least one user in production. I work at Recurly and maintain the official libraries. I've had a couple customers express interest in using this library but no one has used it in production yet (from what I can tell in our logs). If I had at least one user in production, I think I could make the case to mark this as beta and maybe start officially supporting it on Recurly time.

**Comment by blatyo** [comment]
The particular features I intend to use are subscriptions and accounts. But, probably some of the newer features introduced for those, like gift card for payment method. None of the subscriptions will be usage based or have add ons.

My primary goal is getting something working, so I'm not inclined to contribute API changes immediately. That said, I do like the API changes you have suggested. It's very similar to how [ExAws](https://github.com/ex-aws/ex_aws) is designed, which works very well. They still support a global client config, but you have the option to override it at the request level. So, there's no need to pass around an explicit client. 

I'll be starting work on a full integration in a 1.5 weeks and should have something in production 2-4 weeks after that.

**Comment by bhelx** [comment]
Good to hear. Let me know how your integration goes. If I get any time to work on it, I might try updating some things myself. Also, if you have any questions you can email me at ben at recurly.com.

**Pull request merged**
